# -*- coding: utf-8 -*-
"""k-means.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cKww9v04UD0I3cwLdDyqL9GDHLaxWWSk
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans

X, y = make_blobs(n_samples=300, centers=3, random_state=42)


plt.scatter(X[:, 0], X[:, 1], s=50, c='gray')
plt.title("Generated Data")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.show()

kmeans = KMeans(n_clusters=3, random_state=42)
kmeans.fit(X)

centers = kmeans.cluster_centers_
labels = kmeans.labels_

plt.scatter(X[:, 0], X[:, 1], c=labels, cmap='viridis', s=50)
plt.scatter(centers[:, 0], centers[:, 1], c='red', marker='X', s=200, label='Centroids')
plt.title("K-Means Clustering")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.legend()
plt.show()

print("Inertia (within-cluster sum of squares):", kmeans.inertia_)