# -*- coding: utf-8 -*-
"""mini project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WAYo8BmbzD3rzFFOcT7fkPMn7W39-8bH
"""

import torch
import cv2
import pandas as pd


model = torch.hub.load('ultralytics/yolov5', 'yolov5s')


animal_classes = ['person', 'dog', 'cat', 'cow', 'sheep', 'horse', 'elephant', 'bear', 'zebra', 'giraffe']


cap = cv2.VideoCapture(0)

if not cap.isOpened():
    print("Error: Could not open webcam.")
    exit()

print("Webcam opened. Press 'q' to exit.")

while True:
    ret, frame = cap.read()
    if not ret:
        print("Error: Failed to capture frame.")
        break


    results = model(frame)
    detections = results.pandas().xyxy[0]


    for _, row in detections.iterrows():
        class_name = row['name']
        confidence = float(row['confidence'])
        if class_name in animal_classes:

            x1, y1, x2, y2 = int(row['xmin']), int(row['ymin']), int(row['xmax']), int(row['ymax'])
            label = f"{class_name} {confidence:.2f}"

            cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)
            cv2.putText(frame, label, (x1, y1 - 10),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)


    cv2.imshow("Wildlife Detection - Webcam", frame)

    # Exit when 'q' is pressed
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break


cap.release()
cv2.destroyAllWindows()