# -*- coding: utf-8 -*-
"""svm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1apvIV1p3kEeAW4mLnDRRNMo2r3tX0yJ6
"""

from sklearn import datasets
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


iris = datasets.load_iris()
X = iris.data
y = iris.target


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


clf = SVC(kernel='linear')


clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("SVM Classifier Accuracy:", accuracy)